-- 데이터스페이스 생성
CREATE TABLESPACE TREELINK
DATAFILE 'treelink_data01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- 계정 생성 / 권한 부여
CREATE USER TREELINK IDENTIFIED BY TREELINK
DEFAULT TABLESPACE TREELINK
QUOTA UNLIMITED ON TREELINK
GRANT CONNECT, RESOURCE TO TREELINK;
