CREATE TABLE MEMBERS(
  MEMBER_NO NUMBER CONSTRAINT PK_MEMBERS PRIMARY KEY,
  ID VARCHAR2(300) CONSTRAINT NN_MEMBERS_ID NOT NULL,
  PWD VARCHAR2(300) CONSTRAINT NN_MEMBERS_PWD NOT NULL,
  NAME VARCHAR2(300) CONSTRAINT NN_MEMBERS_NAME NOT NULL,
  STATE VARCHAR2(10) DEFAULT 'Y'
)
COMMENT ON TABLE MEMBERS IS '회원';
COMMENT ON COLUMN MEMBERS.MEMBER_NO IS '아이디';
COMMENT ON COLUMN MEMBERS.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBERS.NAME IS '이름';
COMMENT ON COLUMN MEMBERS.STATE IS '회원 상태';

CREATE TABLE ROLES(
  ROLE_NO NUMBER CONSTRAINT PK_ROLES PRIMARY KEY,
  NAME VARCHAR2 CONSTRAINT NN_ROLES_NAME NOT NULL
)
COMMENT ON TABLE ROLES IS '권한';
COMMENT ON COLUMN ROLES.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLES.NAME IS '권한 이름';

CREATE TABLE MEMBER_ROLES(
  MEMBER_NO NUMBER CONSTRAINT FK_MEMBER_ROLES_MEMBER_NO REFERENCES MEMBERS(MEMBER_NO),
  ROLE_NO NUMBER CONSTRAINT FK_MEMBER_ROLES_ROLE_NO REFERENCES ROLES(ROLE_NO)
)
COMMENT ON TABLE MEMBER_ROLES IS '회원-권한';
COMMENT ON COLUMN MEMBER_ROLES.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER_ROLES.ROLE_NAME IS '권한 식별번호';

CREATE TABLE URL_RESOURCES(
  RESOURCES_NO NUMBER CONSTRAINT PK_URL PRIMARY KEY,
  URL_PATTERN VARCHAR2(50) CONSTRAINT NN_URL_PATTERN NOT NULL
)
COMMENT ON TABLE URL_RESOURCES IS 'URL 자원';
COMMENT ON COLUMN URL_RESOURCES.RESOURCES_NO IS 'URL 식별번호';
COMMENT ON COLUMN URL_RESOURCES.URL_PATTERN IS 'URL 패턴';

CREATE TABLE ROLE_RESOURCES(
  ROLE_NO NUMBER CONSTRAINT FK_ROLE_RESOURCES_ROLE_NO REFERENCES ROLES(ROLE_NO),
  RESOURCES_NO NUMBER CONSTRAINT FK_ROLE_RESOURCES_RESOURCES_NO REFERENCES URL_RESOURCES(RESOURCES_NO),
  IS_ALLOWED NUMBER(1) CHECK (IS_ALLOWED IN (0, 1))
)
COMMENT ON TABLE ROLE_RESOURCES IS '권한-URL 자원';
COMMENT ON COLUMN ROLE_RESOURCES.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_RESOURCES.RESOURCES_NO IS '자원 식별번호';
COMMENT ON COLUMN ROLE_RESOURCES.IS_ALLOWED IS '접근가능 여부';

CREATE TABLE COMPANIES(
  COMPANY_NO NUMBER CONSTRAINT PK_COMPANIES PRIMARY KEY,
  COMPANY_NAME VARCHAR2(330) CONSTRAINT NN_COMPANIES_COMPANY_NAME NOT NULL,
  REPRESENTATIVE VARCHAR2(50),
  BUSINESS_TYPE
  REGION
  PHONE VARCHAR2(100),
  EMAIL VARCHAR2(300),
  CREATED_AT DATE,
  UPDATE_AT DATE
)
COMMENT ON TABLE COMPANIES IS '회사';
COMMENT ON COLUMN COMPANIES.COMPANY_NO IS '회사 식별번호';
COMMENT ON COLUMN COMPANIES.REPRESENTATIVE IS '대표 이름';
COMMENT ON COLUMN COMPANIES.BUSINESS_TYPE IS '회사 종류';
COMMENT ON COLUMN COMPANIES.REGION IS '지역';
COMMENT ON COLUMN COMPANIES.PHONE IS '전화번호';
COMMENT ON COLUMN COMPANIES.EMAIL IS '이메일';
COMMENT ON COLUMN COMPANIES.CREATED_AT '창립일';
COMMENT ON COLUMN COMPANIES.UPDATE_AT '갱신일';