CREATE TABLE MEMBER(
  MEMBER_NO NUMBER PRIMARY KEY,
  ID VARCHAR2(300) NOT NULL,
  PWD VARCHAR2(300) NOT NULL,
  NAME VARCHAR2(300) NOT NULL,
  STATE VARCHAR2(10) DEFAULT 'Y'
)
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.STATE IS '회원 상태';

CREATE TABLE ROLE(
  ROLE_NO NUMBER PRIMARY KEY,
  NAME VARCHAR2 NOT NULL
)
COMMENT ON TABLE ROLE IS '권한';
COMMENT ON COLUMN ROLE.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE.NAME IS '권한 이름';

CREATE TABLE MEMBER_ROLE(
  MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO),
  ROLE_NO NUMBER REFERENCES ROLE(ROLE_NO)
)
COMMENT ON TABLE MEMBER_ROLE IS '회원-권한';
COMMENT ON COLUMN MEMBER_ROLE.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER_ROLE.ROLE_NAME IS '권한 식별번호';

CREATE TABLE URL_RESOURCE(
  RESOURCES_NO NUMBER PRIMARY KEY,
  URL_PATTERN VARCHAR2(50) NOT NULL
)
COMMENT ON TABLE URL_RESOURCE IS 'URL 자원';
COMMENT ON COLUMN URL_RESOURCE.RESOURCES_NO IS 'URL 식별번호';
COMMENT ON COLUMN URL_RESOURCE.URL_PATTERN IS 'URL 패턴';

CREATE TABLE ROLE_RESOURCE(
  ROLE_NO NUMBER REFERENCES ROLE(ROLE_NO),
  RESOURCES_NO NUMBER REFERENCES URL_RESOURCE(RESOURCES_NO),
  IS_ALLOWED NUMBER(1) CHECK (IS_ALLOWED IN (0, 1))
)
COMMENT ON TABLE ROLE_RESOURCE IS '권한-URL 자원';
COMMENT ON COLUMN ROLE_RESOURCE.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_RESOURCE.RESOURCES_NO IS '자원 식별번호';
COMMENT ON COLUMN ROLE_RESOURCE.IS_ALLOWED IS '접근가능 여부';

CREATE TABLE COMPANY(
  COMPANY_NO NUMBER PRIMARY KEY,
  COMPANY_NAME VARCHAR2(330) NOT NULL,
  REPRESENTATIVE VARCHAR2(50),
  BUSINESS_TYPE
  REGION
  PHONE VARCHAR2(100),
  EMAIL VARCHAR2(300),
  CREATED_AT DATE,
  UPDATE_AT DATE
)
COMMENT ON TABLE COMPANY IS '회사';
COMMENT ON COLUMN COMPANY.COMPANY_NO IS '회사 식별번호';
COMMENT ON COLUMN COMPANY.REPRESENTATIVE IS '대표 이름';
COMMENT ON COLUMN COMPANY.BUSINESS_TYPE IS '회사 종류';
COMMENT ON COLUMN COMPANY.REGION IS '지역';
COMMENT ON COLUMN COMPANY.PHONE IS '전화번호';
COMMENT ON COLUMN COMPANY.EMAIL IS '이메일';
COMMENT ON COLUMN COMPANY.CREATED_AT '창립일';
COMMENT ON COLUMN COMPANY.UPDATE_AT '갱신일';