CREATE SEQUENCE SEQ_MEMBERS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_COMPANIES
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_ROLES
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_URL_RESOURCES
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_EVALUATIONS
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_EVIDENCES
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;