-- MEMBER추가하면 MEMBER-ROLE테이블에 권한 추가하기
CREATE OR REPLACE TRIGGER TRG_NEW_MEMBER
AFTER INSERT ON MEMBER
FOR EACH ROW
BEGIN
    INSERT INTO MEMBER_ROLE (MEMBER_NO, ROLE_NO)
    VALUES (:NEW.MEMBER_NO, 3);
END;
/