INSERT ALL
  INTO ROLES (ROLE_NO, NAME) VALUES (SEQ_MEMBERS.nextval, ROLE_ADMIN)
  INTO ROLES (ROLE_NO, NAME) VALUES (SEQ_MEMBERS.nextval, ROLE_EVALUATOR)
  INTO ROLES (ROLE_NO, NAME) VALUES (SEQ_MEMBERS.nextval, ROLE_VIEWER)

SELECT * FROM DUAL;