#로컬용 설정

# 바이너리 데이터 저장 경로
file.upload.address=D:/Dev/upload/

#오라클 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/freepdb1

spring.datasource.username=TREELINK
spring.datasource.password=TREELINK