-- =========================================
-- MEMBER 더미 데이터 (ROLE_ADMIN 5명)
-- =========================================
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('admin01', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '김도윤', '도윤이', '011-1111-1101');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('admin02', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '이서준', '서준이', '011-1111-1102');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('admin03', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '박지호', '지호쨩', '011-1111-1103');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('admin04', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '최하은', '하은이', '011-1111-1104');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('admin05', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '정유진', '유진짱', '011-1111-1105');

-- =========================================
-- MEMBER 더미 데이터 (ROLE_EVALUATOR 5명)
-- =========================================
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('eval01', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '한지민', '지민이', '011-1111-1201');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('eval02', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '오세훈', '세훈이', '011-1111-1202');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('eval03', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '강수아', '수아쨩', '011-1111-1203');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('eval04', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '윤재원', '재원이', '011-1111-1204');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('eval05', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '임나연', '나연짱', '011-1111-1205');

-- =========================================
-- MEMBER 더미 데이터 (ROLE_VIEWER 5명)
-- =========================================
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('viewer01', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '서지안', '지안이', '011-1111-1301');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('viewer02', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '문채원', '채원짱', '011-1111-1302');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('viewer03', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '신동현', '동현이', '011-1111-1303');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('viewer04', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '배소연', '소연이', '011-1111-1304');
INSERT INTO MEMBER (ID, PWD, NAME, NICKNAME, PHONE) VALUES ('viewer05', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '조민석', '민석짱', '011-1111-1305');


-- =========================================
-- MEMBER_ROLE 권한 변경 (트리거로 생성된 기본 행을 UPDATE)
-- ROLE_NO: 2=ROLE_ADMIN, 3=ROLE_EVALUATOR, 4=ROLE_VIEWER
-- =========================================

-- ROLE_ADMIN 적용
UPDATE MEMBER_ROLE SET ROLE_NO = 2 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'admin01');
UPDATE MEMBER_ROLE SET ROLE_NO = 2 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'admin02');
UPDATE MEMBER_ROLE SET ROLE_NO = 2 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'admin03');
UPDATE MEMBER_ROLE SET ROLE_NO = 2 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'admin04');
UPDATE MEMBER_ROLE SET ROLE_NO = 2 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'admin05');

-- ROLE_EVALUATOR 적용
UPDATE MEMBER_ROLE SET ROLE_NO = 3 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'eval01');
UPDATE MEMBER_ROLE SET ROLE_NO = 3 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'eval02');
UPDATE MEMBER_ROLE SET ROLE_NO = 3 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'eval03');
UPDATE MEMBER_ROLE SET ROLE_NO = 3 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'eval04');
UPDATE MEMBER_ROLE SET ROLE_NO = 3 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'eval05');

-- ROLE_VIEWER 적용 (트리거 기본값과 동일하지만 명시적으로 재확인)
UPDATE MEMBER_ROLE SET ROLE_NO = 4 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'viewer01');
UPDATE MEMBER_ROLE SET ROLE_NO = 4 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'viewer02');
UPDATE MEMBER_ROLE SET ROLE_NO = 4 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'viewer03');
UPDATE MEMBER_ROLE SET ROLE_NO = 4 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'viewer04');
UPDATE MEMBER_ROLE SET ROLE_NO = 4 WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE ID = 'viewer05');

COMMIT;