-- =========================================
-- COMPANY 더미 데이터 (15개, 벌초/조경 관련 업체)
-- =========================================

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100001', '푸른숲조경', '김태윤', '02-511-0011', 'contact@pureunsup.example.com', TO_DATE('12/03/15','RR/MM/DD'),
TO_CLOB(q'[<h1>푸른숲조경입니다</h1><p>저희는 <b>벌초와 정원 관리</b>를 전문으로 하는 업체입니다.</p><ul><li>15년 이상의 현장 경험</li><li>공공기관 및 개인 정원 관리 다수 수행</li></ul><p><img src="https://picsum.photos/seed/tree1/400/200"></p>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100002', '한마음조경', '이수경', '02-511-0022', 'info@hanmaeum.example.com', TO_DATE('15/07/22','RR/MM/DD'),
TO_CLOB(q'[<h1>한마음조경</h1><p>정직하고 <u>꼼꼼한 작업</u>으로 신뢰받는 조경업체입니다.</p><p>운동장 관리부터 실내조경까지 폭넓게 서비스합니다.</p>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100003', '그린벌초단', '박준호', '02-511-0033', 'green@greenbulcho.example.com', TO_DATE('18/09/01','RR/MM/DD'),
TO_CLOB(q'[<h1>그린벌초단</h1><p>벌초 전문 인력이 <b>신속하고 안전하게</b> 작업합니다.</p><ol><li>사전 현장 답사</li><li>당일 작업 완료 사진 전송</li></ol>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100004', '대한조경시설', '최영수', '02-511-0044', 'info@daehanjs.example.com', TO_DATE('10/01/10','RR/MM/DD'),
TO_CLOB(q'[<h1>대한조경시설</h1><p>공공기관 조경시설물 설치 및 유지관리 <b>다수 계약 경험</b>이 있습니다.</p><p><img src="https://picsum.photos/seed/tree2/400/200"></p>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100005', '초록정원', '정민아', '02-511-0055', 'hello@chorokgarden.example.com', TO_DATE('19/05/05','RR/MM/DD'),
TO_CLOB(q'[<h1>초록정원</h1><p>아름다운 정원 설계와 관리를 함께 합니다.</p><ul><li>개인 정원 디자인</li><li>계절별 식재 관리</li></ul>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100006', '뿌리깊은조경', '한상철', '02-511-0066', 'contact@ppuri.example.com', TO_DATE('14/11/20','RR/MM/DD'),
TO_CLOB(q'[<h1>뿌리깊은조경</h1><p><b>30년 전통</b>의 조경 전문 업체입니다.</p><p>운동장, 스포츠 시설 조경에 강점이 있습니다.</p>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100007', '실내조경플러스', '오지현', '02-511-0077', 'plus@indoorplus.example.com', TO_DATE('21/02/14','RR/MM/DD'),
TO_CLOB(q'[<h1>실내조경플러스</h1><p>사무실, 상업공간 실내조경을 전문으로 합니다.</p><p><img src="https://picsum.photos/seed/tree3/400/200"></p>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100008', '청산벌초', '윤도현', '02-511-0088', 'info@cheongsan.example.com', TO_DATE('17/06/18','RR/MM/DD'),
TO_CLOB(q'[<h1>청산벌초</h1><p>산소 벌초부터 인근 정리까지 <u>깔끔하게</u> 마무리합니다.</p>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100009', '스포츠그린', '장미영', '02-511-0099', 'contact@sportsgreen.example.com', TO_DATE('16/08/09','RR/MM/DD'),
TO_CLOB(q'[<h1>스포츠그린</h1><p>축구장, 야구장 등 <b>운동장 잔디 관리</b> 전문 업체입니다.</p><p><img src="https://picsum.photos/seed/tree4/400/200"></p>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100010', '나무와사람', '서지훈', '02-511-0100', 'namu@namusaram.example.com', TO_DATE('13/04/25','RR/MM/DD'),
TO_CLOB(q'[<h1>나무와사람</h1><p>사람과 자연이 함께하는 조경을 지향합니다.</p><ul><li>정원 리모델링</li><li>노목 관리</li></ul>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100011', '푸른동산', '임재영', '02-511-0111', 'info@pureundongsan.example.com', TO_DATE('20/10/30','RR/MM/DD'),
TO_CLOB(q'[<h1>푸른동산</h1><p>공공기관 조경 유지관리 계약을 다수 수행했습니다.</p><p><b>신속한 A/S</b>가 강점입니다.</p>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100012', '자연과조경', '문세영', '02-511-0122', 'contact@jayeongwa.example.com', TO_DATE('11/12/12','RR/MM/DD'),
TO_CLOB(q'[<h1>자연과조경</h1><p>친환경 조경 자재만을 사용합니다.</p><p><img src="https://picsum.photos/seed/tree5/400/200"></p>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100013', '한별조경시설', '배성훈', '02-511-0133', 'info@hanbyul.example.com', TO_DATE('09/09/09','RR/MM/DD'),
TO_CLOB(q'[<h1>한별조경시설</h1><p>조경시설물 설치 및 보수 전문입니다.</p><ol><li>파고라 설치</li><li>벤치 및 데크 시공</li></ol>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100014', '늘푸른가드닝', '조은비', '02-511-0144', 'hello@neulpureun.example.com', TO_DATE('22/01/03','RR/MM/DD'),
TO_CLOB(q'[<h1>늘푸른가드닝</h1><p>사계절 아름다운 정원을 만들어 드립니다.</p><p><b>맞춤 컨설팅</b> 제공합니다.</p>]'), 'ACTIVE');

INSERT INTO COMPANY (BUSINESS_NO, COMPANY_NAME, REPRESENTATIVE_NAME, PHONE, EMAIL, CREATED_ON, INTRO, STATUS)
VALUES ('1010100015', '터전조경', '남기훈', '02-511-0155', 'contact@teojeon.example.com', TO_DATE('08/06/06','RR/MM/DD'),
TO_CLOB(q'[<h1>터전조경</h1><p>벌초, 정원, 실내조경까지 <b>원스톱 서비스</b>를 제공합니다.</p><p><img src="https://picsum.photos/seed/tree6/400/200"></p>]'), 'ACTIVE');


-- =========================================
-- COMPANY_SPECIALTY 더미 데이터 (업체당 1~3개 종목)
-- =========================================

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100001'), 1, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100001'), 4, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100002'), 2, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100002'), 5, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100003'), 1, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100004'), 3, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100004'), 6, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100005'), 4, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100006'), 2, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100006'), 4, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100006'), 6, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100007'), 5, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100008'), 1, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100008'), 99, '묘지 주변 잡초 제거 및 벌목 서비스도 함께 제공');

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100009'), 2, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100010'), 4, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100010'), 99, '고목 및 노거수 특수 관리 서비스');

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100011'), 3, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100011'), 6, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100012'), 4, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100012'), 5, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100013'), 6, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100014'), 4, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100014'), 5, NULL);

INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100015'), 1, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100015'), 4, NULL);
INSERT INTO COMPANY_SPECIALTY (COMPANY_NO, SPECIALTY_NO, MEMO)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO = '1010100015'), 5, NULL);

COMMIT;