-- =========================================
-- LOCATION 더미 데이터 (실제 정원/수목원 + 가상 위치)
-- =========================================

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (34.9350, 127.4489, '전남 순천시 국가정원1호길 47', '전남', '순천시');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (35.5497, 129.2933, '울산 중구 태화강변길 242', '울산', '중구');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (37.7891, 127.3489, '경기 가평군 상면 수목원로 432', '경기', '가평군');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (37.7580, 127.1611, '경기 포천시 소흘읍 광릉수목원로 509', '경기', '포천시');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (36.3719, 127.3853, '대전 서구 둔산대로 169', '대전', '서구');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (36.5136, 126.3222, '충남 태안군 안면읍 꽃지1길 390', '충남', '태안군');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (37.5486, 127.3339, '경기 양평군 양서면 세미원길 27', '경기', '양평군');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (35.3225, 126.9886, '전남 담양군 담양읍 죽녹원로 119', '전남', '담양군');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (35.1611, 129.0533, '부산 부산진구 시민공원로 73', '부산', '부산진구');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (36.6003, 127.4890, '충북 청주시 상당구 남일면 남석로 580', '충북', '청주시 상당구');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (33.3010, 126.6314, '제주 서귀포시 남원읍 신례동로 256', '제주', '서귀포시');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (36.4772, 126.3011, '충남 태안군 안면읍 안면대로 3195', '충남', '태안군');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (37.3572, 127.9028, '강원 원주시 지정면 작당길 26', '강원', '원주시');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (37.8887, 127.7908, '강원 춘천시 동면 금옥길 171-12', '강원', '춘천시');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (35.5194, 129.2947, '울산 남구 남부순환도로 155', '울산', '남구');

-- 가상 위치 (조경 관련 임의 좌표, 한국 내부)
INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (36.8014, 127.0089, '충남 천안시 조경단지길 12', '충남', '천안시');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (35.8722, 128.6011, '경북 경산시 정원로 88', '경북', '경산시');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (37.2751, 127.0089, '경기 용인시 처인구 화훼단지로 21', '경기', '용인시 처인구');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (35.1796, 126.9077, '광주 북구 조경산업로 45', '광주', '북구');

INSERT INTO LOCATION (LATITUDE, LONGITUDE, ADDRESS, SIDO, SIGUNGU)
VALUES (36.1049, 128.4162, '경북 구미시 그린단지길 7', '경북', '구미시');

-- =========================================
-- COMPANY_LOCATION 더미 데이터 (업체마다 1~2개)
-- =========================================

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100001'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='전남 순천시 국가정원1호길 47'), '순천 현장');
INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100001'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='경기 가평군 상면 수목원로 432'), '가평 현장');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100002'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='대전 서구 둔산대로 169'), '한밭 현장');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100003'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='충남 천안시 조경단지길 12'), '천안 현장');
INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100003'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='경북 경산시 정원로 88'), '경산 현장');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100004'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='부산 부산진구 시민공원로 73'), '부산시민공원');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100005'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='경기 양평군 양서면 세미원길 27'), '세미원 현장');
INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100005'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='경기 용인시 처인구 화훼단지로 21'), '용인 현장');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100006'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='울산 남구 남부순환도로 155'), '울산대공원');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100007'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='제주 서귀포시 남원읍 신례동로 256'), '제주 치유의정원');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100008'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='전남 담양군 담양읍 죽녹원로 119'), '죽녹원 현장');
INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100008'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='광주 북구 조경산업로 45'), '광주 현장');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100009'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='울산 중구 태화강변길 242'), '태화강국가정원');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100010'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='강원 원주시 지정면 작당길 26'), '원주식물원');
INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100010'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='강원 춘천시 동면 금옥길 171-12'), '춘천식물원');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100011'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='경기 포천시 소흘읍 광릉수목원로 509'), '국립수목원');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100012'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='충북 청주시 상당구 남일면 남석로 580'), '청주식물원');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100013'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='경북 구미시 그린단지길 7'), '구미 현장');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100014'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='충남 태안군 안면읍 꽃지1길 390'), '꽃지해안공원');
INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100014'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='충남 태안군 안면읍 안면대로 3195'), '안면도수목원');

INSERT INTO COMPANY_LOCATION (COMPANY_NO, LOCATION_NO, NAME) VALUES
((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100015'), (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='경기 용인시 처인구 화훼단지로 21'), '용인 현장');

-- =========================================
-- MANAGEMENT_STATUS 더미 데이터 (6개, treelink_legacy 패턴 참고)
-- =========================================

INSERT INTO MANAGEMENT_STATUS (COMPANY_NO, LOCATION_NO, NAME, MEMO, START_ON, END_ON, VISIBLE, STATUS)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100001'),
        (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='전남 순천시 국가정원1호길 47'),
        '순천 정원 정비', '가을철 정원 전체 정비 작업', TO_DATE('26/03/10','RR/MM/DD'), TO_DATE('26/06/10','RR/MM/DD'), 'ALL', 'FINISHED');

INSERT INTO MANAGEMENT_STATUS (COMPANY_NO, LOCATION_NO, NAME, MEMO, START_ON, END_ON, VISIBLE, STATUS)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100002'),
        (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='대전 서구 둔산대로 169'),
        '한밭수목원 관리', '월 1회 정기 점검 및 병해충 방제', TO_DATE('26/05/01','RR/MM/DD'), TO_DATE('26/12/31','RR/MM/DD'), 'ALL', 'ONGOING');

INSERT INTO MANAGEMENT_STATUS (COMPANY_NO, LOCATION_NO, NAME, MEMO, START_ON, END_ON, VISIBLE, STATUS)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100003'),
        (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='충남 천안시 조경단지길 12'),
        '천안 벌초 작업', '산소 주변 벌초 및 정리', TO_DATE('26/08/01','RR/MM/DD'), TO_DATE('26/08/15','RR/MM/DD'), 'SEMI', 'READY');

INSERT INTO MANAGEMENT_STATUS (COMPANY_NO, LOCATION_NO, NAME, MEMO, START_ON, END_ON, VISIBLE, STATUS)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100004'),
        (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='부산 부산진구 시민공원로 73'),
        '부산시민공원 시설 보수', '벤치 및 파고라 보수 작업', TO_DATE('26/02/15','RR/MM/DD'), TO_DATE('26/04/20','RR/MM/DD'), 'HIDDEN', 'CANCELLED');

INSERT INTO MANAGEMENT_STATUS (COMPANY_NO, LOCATION_NO, NAME, MEMO, START_ON, END_ON, VISIBLE, STATUS)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100006'),
        (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='울산 남구 남부순환도로 155'),
        '울산대공원 잔디관리', '운동장 잔디 파종 및 관리', TO_DATE('26/04/01','RR/MM/DD'), TO_DATE('26/10/31','RR/MM/DD'), 'ALL', 'ONGOING');

INSERT INTO MANAGEMENT_STATUS (COMPANY_NO, LOCATION_NO, NAME, MEMO, START_ON, END_ON, VISIBLE, STATUS)
VALUES ((SELECT COMPANY_NO FROM COMPANY WHERE BUSINESS_NO='1010100009'),
        (SELECT LOCATION_NO FROM LOCATION WHERE ADDRESS='울산 중구 태화강변길 242'),
        '태화강국가정원 리모델링', '화단 리모델링 및 조형물 설치', TO_DATE('25/12/01','RR/MM/DD'), TO_DATE('26/03/01','RR/MM/DD'), 'SEMI', 'FINISHED');

COMMIT;