spring.application.name=treelink

# 배포에 따라 설정 파일 구분
spring.profiles.active=local

# 서버 포트번호
server.port=8080

# Thymeleaf 머릿말 꼬릿말
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#파일 업로드용 MultipartResolver
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ContextRoot 설정
server.servlet.context-path=/

# 마이바티스 설정 
mybatis.mapper-locations=classpath:mappers/*.xml

# ORACLE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# xml설정 파일을 대신 둬 버그를 회피할 거에요
mybatis.config-location=classpath:config/mybatis-config.xml

# 추가 설정 파일 인식
spring.config.import=optional:classpath:config/key.properties,classpath:config/common.properties