CREATE TABLE MEMBER(
  MEMBER_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID VARCHAR2(300) NOT NULL,
  PWD VARCHAR2(300) NOT NULL,
  NAME VARCHAR2(300) NOT NULL,
  NICKNAME VARCHAR2(300) NOT NULL,
  PHONE VARCHAR2(15),
  STATUS VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL
);
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.NICKNAME IS '별명';
COMMENT ON COLUMN MEMBER.PHONE IS '연락처';
COMMENT ON COLUMN MEMBER.STATUS IS '상태';


CREATE TABLE ROLE_INFO(
  ROLE_NO NUMBER PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL
);
COMMENT ON TABLE ROLE_INFO IS '권한';
COMMENT ON COLUMN ROLE_INFO.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_INFO.NAME IS '권한 이름';


CREATE TABLE MEMBER_ROLE(
  MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO),
  ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO)
);
COMMENT ON TABLE MEMBER_ROLE IS '회원-권한';
COMMENT ON COLUMN MEMBER_ROLE.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER_ROLE.ROLE_NO IS '권한 식별번호';


CREATE TABLE COMPANY(
  COMPANY_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BUSINESS_NO VARCHAR2(15) NOT NULL UNIQUE,
  COMPANY_NAME VARCHAR2(330) NOT NULL,
  REPRESENTATIVE_NAME VARCHAR2(33) NOT NULL,
  PHONE VARCHAR2(15) NOT NULL,
  EMAIL VARCHAR2(100),
  CREATED_ON DATE NOT NULL,
  INTRO CLOB,
  STATUS VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL
);
COMMENT ON TABLE COMPANY IS '업체';
COMMENT ON COLUMN COMPANY.COMPANY_NO IS '업체 식별번호';
COMMENT ON COLUMN COMPANY.BUSINESS_NO IS '사업자 등록번호';
COMMENT ON COLUMN COMPANY.COMPANY_NAME IS '업체 이름';
COMMENT ON COLUMN COMPANY.REPRESENTATIVE_NAME IS '대표 이름';
COMMENT ON COLUMN COMPANY.PHONE IS '전화번호';
COMMENT ON COLUMN COMPANY.EMAIL IS '이메일';
COMMENT ON COLUMN COMPANY.CREATED_ON IS '창립일';
COMMENT ON COLUMN COMPANY.INTRO IS '소개문';
COMMENT ON COLUMN COMPANY.STATUS IS '상태';


CREATE TABLE ADDRESS(
  ADDRESS_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  LATITUDE NUMBER,
  LONGITUDE NUMBER,
  ROAD_NAME VARCHAR2(330),
  SIDO VARCHAR2(70),
  SIGUNGU VARCHAR2(70)
);
COMMENT ON TABLE ADDRESS IS '업체 주소';
COMMENT ON COLUMN ADDRESS.ADDRESS_NO IS '업체 식별번호';
COMMENT ON COLUMN ADDRESS.LATITUDE IS '위도';
COMMENT ON COLUMN ADDRESS.LONGITUDE IS '경도';
COMMENT ON COLUMN ADDRESS.ROAD_NAME IS '도로명주소';
COMMENT ON COLUMN ADDRESS.SIDO IS '시/도';
COMMENT ON COLUMN ADDRESS.SIGUNGU IS '시/군/구';


CREATE TABLE COMPANY_ADDRESS(
  COMPANY_NO NUMBER REFERENCES COMPANY(COMPANY_NO) NOT NULL,
  ADDRESS_NO NUMBER REFERENCES ADDRESS(ADDRESS_NO) NOT NULL
);
COMMENT ON TABLE COMPANY_ADDRESS IS '업체-주소';
COMMENT ON COLUMN COMPANY_ADDRESS.COMPANY_NO IS '업체 식별번호';
COMMENT ON COLUMN COMPANY_ADDRESS.ADDRESS_NO IS '주소 식별번호';


CREATE TABLE SPECIALTY(
  SPECIALTY_NO NUMBER(2) PRIMARY KEY,
  FIELD VARCHAR2(70) NOT NULL
);
COMMENT ON TABLE SPECIALTY IS '주 종목';
COMMENT ON COLUMN SPECIALTY.SPECIALTY_NO IS '종목 식별번호';
COMMENT ON COLUMN SPECIALTY.FIELD IS '종목';


CREATE TABLE COMPANY_SPECIALTY(
  COMPANY_NO NUMBER REFERENCES COMPANY(COMPANY_NO) NOT NULL,
  SPECIALTY_NO NUMBER REFERENCES SPECIALTY(SPECIALTY_NO) NOT NULL,
  MEMO VARCHAR2(70)
);
COMMENT ON TABLE COMPANY_SPECIALTY IS '업체-주 종목';
COMMENT ON COLUMN COMPANY_SPECIALTY.COMPANY_NO IS '업체 식별번호';
COMMENT ON COLUMN COMPANY_SPECIALTY.SPECIALTY_NO IS '종목 식별번호';
COMMENT ON COLUMN COMPANY_SPECIALTY.MEMO IS '기타종목 메모';


CREATE TABLE EVALUATION(
  EVALUATION_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EVALUATION_UUID VARCHAR2(36) NOT NULL UNIQUE,
  EVALUATION_TARGET NUMBER REFERENCES COMPANY(COMPANY_NO) NOT NULL,
  EVALUATE_BY NUMBER REFERENCES MEMBER(MEMBER_NO) NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  STATUS VARCHAR2(10)
);
COMMENT ON TABLE EVALUATION IS '평가';
COMMENT ON COLUMN EVALUATION.EVALUATION_NO IS '평가 식별번호';
COMMENT ON COLUMN EVALUATION.EVALUATION_UUID IS '평가 식별 UUID';
COMMENT ON COLUMN EVALUATION.EVALUATION_TARGET IS '평가 대상';
COMMENT ON COLUMN EVALUATION.EVALUATE_BY IS '평가자';
COMMENT ON COLUMN EVALUATION.START_DATE IS '시작 시각';
COMMENT ON COLUMN EVALUATION.END_DATE IS '종료 시각';
COMMENT ON COLUMN EVALUATION.STATUS IS '상태';


CREATE TABLE EVALUATION_ITEM(
  ITEM_NO NUMBER PRIMARY KEY,
  FIELD VARCHAR2(70)
);
COMMENT ON TABLE EVALUATION_ITEM IS '평가 항목';
COMMENT ON COLUMN EVALUATION_ITEM.FIELD IS '항목';


CREATE TABLE EVALUATION_SCORE(
  EVALUATION_NO NUMBER REFERENCES EVALUATION(EVALUATION_NO),
  ITEM_NO NUMBER REFERENCES EVALUATION_ITEM(ITEM_NO),
  SCORE NUMBER NOT NULL,
  RESON CLOB NOT NULL
);
COMMENT ON TABLE EVALUATION_SCORE IS '평가 항목';
COMMENT ON COLUMN EVALUATION_SCORE.EVALUATION_NO IS '항목 식별번호';
COMMENT ON COLUMN EVALUATION_SCORE.ITEM_NO IS '항목';
COMMENT ON COLUMN EVALUATION_SCORE.SCORE IS '점수';
COMMENT ON COLUMN EVALUATION_SCORE.RESON IS '이유';


CREATE TABLE EVALUATION_SCORE_HISTORY(
  EVALUATION_NO NUMBER REFERENCES EVALUATION(EVALUATION_NO),
  ITEM_NO NUMBER REFERENCES EVALUATION_ITEM(ITEM_NO),
  SCORE NUMBER NOT NULL,
  RESON CLOB NOT NULL,
  ACTION_AT DATE DEFAULT SYSDATE,
  ACTION_BY REFERENCES MEMBER(MEMBER_NO) NOT NULL,
  ACTION_RESON CLOB NOT NULL
);
COMMENT ON TABLE EVALUATION_SCORE_HISTORY IS '평가 항목';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.EVALUATION_NO IS '항목 식별번호';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.ITEM_NO IS '항목';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.SCORE IS '점수';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.RESON IS '이유';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.ACTION_AT IS '변경 시각';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.ACTION_BY IS '변경자';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.ACTION_RESON IS '변경 이유';


CREATE TABLE FILE_INFO(
  FILE_NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ORIGINAL_NAME VARCHAR2(330) NOT NULL,
  CHANGED_NAME VARCHAR2(50) NOT NULL,
  MIME VARCHAR2(50) NOT NULL,
  FILE_SIZE NUMBER NOT NULL,
  SAVE_PATH VARCHAR2(50) NOT NULL,
  EXPIRE_ON DATE
);
COMMENT ON TABLE FILE_INFO IS '파일';
COMMENT ON COLUMN FILE_INFO.FILE_NO IS '파일 식별번호';
COMMENT ON COLUMN FILE_INFO.ORIGINAL_NAME IS '원본 이름';
COMMENT ON COLUMN FILE_INFO.CHANGED_NAME IS '변경된 이름';
COMMENT ON COLUMN FILE_INFO.MIME IS 'MIME 타입';
COMMENT ON COLUMN FILE_INFO.FILE_SIZE IS '크기';
COMMENT ON COLUMN FILE_INFO.SAVE_PATH IS '저장 경로';
COMMENT ON COLUMN FILE_INFO.EXPIRE_ON IS '만료일';


CREATE TABLE FILE_HISTORY(
  HISTORY_NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  FILE_NO NUMBER REFERENCES FILE_INFO(FILE_NO) ON DELETE SET NULL,
  ORIGINAL_NAME VARCHAR2(330) NOT NULL,
  CHANGED_NAME VARCHAR2(50) NOT NULL,
  SAVE_PATH VARCHAR2(50) NOT NULL,
  ACTION VARCHAR2(10) NOT NULL,
  ACTION_AT DATE DEFAULT SYSDATE,
  ACTION_BY NUMBER REFERENCES MEMBER(MEMBER_NO)
);
COMMENT ON TABLE FILE_HISTORY IS '파일 기록';
COMMENT ON COLUMN FILE_HISTORY.FILE_NO IS '파일 식별번호';
COMMENT ON COLUMN FILE_HISTORY.ORIGINAL_NAME IS '원본 이름';
COMMENT ON COLUMN FILE_HISTORY.CHANGED_NAME IS '변경된 이름';
COMMENT ON COLUMN FILE_HISTORY.SAVE_PATH IS '저장 경로';
COMMENT ON COLUMN FILE_HISTORY.ACTION IS '변경 상태';
COMMENT ON COLUMN FILE_HISTORY.ACTION_AT IS '변경 시각';
COMMENT ON COLUMN FILE_HISTORY.ACTION_BY IS '변경자';


CREATE TABLE EVALUATION_DOC(
  EVALUATION_NO NUMBER REFERENCES EVALUATION(EVALUATION_NO) NOT NULL,
  FILE_NO NUMBER REFERENCES FILE_INFO(FILE_NO) ON DELETE CASCADE NOT NULL,
  DOC_TYPE VARCHAR2(70)
);
COMMENT ON TABLE EVALUATION_DOC IS '평가 서류';
COMMENT ON COLUMN EVALUATION_DOC.EVALUATION_NO IS '평가 식별번호';
COMMENT ON COLUMN EVALUATION_DOC.FILE_NO IS '파일 식별번호';
COMMENT ON COLUMN EVALUATION_DOC.DOC_TYPE IS '서류 종류';


CREATE TABLE COMPANY_DOC(
  COMPANY_NO NUMBER REFERENCES COMPANY(COMPANY_NO) NOT NULL,
  FILE_NO NUMBER REFERENCES FILE_INFO(FILE_NO) ON DELETE CASCADE NOT NULL,
  DOC_TYPE VARCHAR2(70)
);
COMMENT ON TABLE COMPANY_DOC IS '업체 서류';
COMMENT ON COLUMN COMPANY_DOC.COMPANY_NO IS '회사 식별번호';
COMMENT ON COLUMN COMPANY_DOC.FILE_NO IS '파일 식별번호';
COMMENT ON COLUMN COMPANY_DOC.DOC_TYPE IS '서류 종류';
