INSERT ALL
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (1, 'ROLE_ADMIN')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (2, 'ROLE_EVALUATOR')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (3, 'ROLE_VIEWER')

  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (1, '벌초')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (2, '초화류 식재')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (3, '수목 식재')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (4, '전정 및 가지치기')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (5, '예초 및 제초')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (6, '병해충 방제')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (7, '관수 관리')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (8, '잔디 관리')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (9, '하자 보수')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (10, '정기 유지관리')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (11, '조경시설물 관리')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (12, '기타')
SELECT * FROM DUAL;

COMMIT;