INSERT ALL
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (1, 'ROLE_SUPER_ADMIN')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (2, 'ROLE_ADMIN')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (3, 'ROLE_EVALUATOR')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (4, 'ROLE_VIEWER')

  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (1, '벌초')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (2, '운동장 / 스포츠')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (3, '공공기관 유지관리')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (4, '정원')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (5, '실내조경')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (6, '조경시설물')
  INTO SPECIALTY (SPECIALTY_NO, FIELD) VALUES (99, '기타')

  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (10, '투명성 종합')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (11, '작업 정보 공개')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (12, '비용 투명성')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (13, '결과 공유')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (20, '책임성 종합')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (21, '작업 이행률')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (22, '하자 대응')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (23, '민원 대응')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (24, '사후 관리')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (30, '신뢰성 종합')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (31, '일정 준수')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (32, '서비스 일관성')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (33, '사용자 평가')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (34, '재이용 의사')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (40, '보너스 종합')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (41, '환경')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (42, '사회')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (43, '거버넌스')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (1, '최종 종합')
  INTO EVALUATION_ITEM(ITEM_NO, FIELD) VALUES (2, '최종 참조 종합')

  -- 최고 관리자 계정 생성
  INTO MEMBER(ID, PWD, NAME, NICKNAME) VALUES ('asdf', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '최고 관리자', '최고 관리자')

SELECT 1 FROM DUAL;


-- 최고 관리자 권한 수정
UPDATE MEMBER_ROLE
SET ROLE_NO = 1
WHERE MEMBER_NO = 1;


-- 최고 관리자 권한 추가
INSERT ALL
  INTO MEMBER_ROLE(MEMBER_NO, ROLE_NO) VALUES(1,2)
SELECT 1 FROM DUAL;

COMMIT;